version: "3.5"

services:

  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    image: base

  user-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    container_name: user_app
    ports:
      - "4004:4004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=userjwtsecret
      - NEXTAUTH_URL=http://localhost:4004
      - JWT_SECRET=myjwtsecret

  merchant-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.merchant
    container_name: merchant_app
    ports:
      - "4005:4005"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - GOOGLE_CLIENT_ID=""
      - GOOGLE_CLIENT_SECRET=""
      - GITHUB_ID=""
      - GITHUB_SECRET=""
      - NEXTAUTH_URL=http://localhost:4005
      - NEXTAUTH_SECRET=merchantjwtsecret

  bank-webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.bank-webhook
    container_name: bank_webhook
    ports:
      - "4006:4006"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - BWS_TOKEN_VAL=mybwstoken

  bankservice-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.bankservice-app
    container_name: bankservice_app
    ports:
      - "4007:4007"
    environment:
      - VITE_BWS_TOKEN_VAL=mybwstoken
      - VITE_FINTRANSACT_FRONTEND_URL=http://localhost:4004 # to redirect back via window.href - let it be like this only (localhost)
      - VITE_FINTRANSACT_BANKSERVICE_BE_URL=http://localhost:4008 # this also remains localhost, because this is frontend container
      # main code resides in browser, js that side sends request, their is no inter microservice (containers) sort of communication
      # in same mac machine, both are different things, when bankservice-be is communicating with bank-webhook, both are actually
      # running as containers in local mac machine, thats not the case for this front end side code.

  bankservice-be:
    build:
      context: .
      dockerfile: docker/Dockerfile.bankservice-be
    container_name: bankservice_be
    ports:
      - "4008:4008"
    environment:
      - BWS_TOKEN_VAL=mybwstoken
      - WEBHOOK_BACKEND_URL=http://bank-webhook:4006

  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    external: false
