# Dockerfile.base
FROM node:lts-alpine AS base

# Install PostgreSQL client to use pg_isready, bash, and dos2unix
RUN apk --no-cache add postgresql-client bash dos2unix

# Create a shared directory for the apps
WORKDIR /app

# Copy package files for all apps first
COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Copy start.sh script
COPY scripts/start.sh /app/start.sh
